target 'HelloJsWorld (iOS)' do
  platform :ios, '10.0'
  use_frameworks!

  # Pods for HelloJsWorld (iOS)
  pod 'bionicjs', :path => '../../../bionic-js-swift'

end

target 'HelloJsWorld (macOS)' do
  platform :macos, '10.12'
  use_frameworks!

  # Pods for HelloJsWorld (macOS)
  pod 'bionicjs', :path => '../../../bionic-js-swift'

end
