name: Release bionic.js Tool

on:
  push:
    paths:
      - 'bionic-js-tool/**'
    tags:
      - 'release/**'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Cache NPM packages
        uses: actions/cache@v2
        with:
          path: bionic-js-tool/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('bionic-js-tool/package.json') }}
          restore-keys: ${{ runner.os }}-npm
      - name: Build and test
        working-directory: ./bionic-js-tool
        run: |
          npm ci
          npm test
      - name: Publish to NPM
        working-directory: ./bionic-js-tool
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}