# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GeoPoint (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Bjs', :path => '../../../bionic-js-swift'

end

target 'GeoPoint (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Bjs', :path => '../../../bionic-js-swift'

end
